export const AIRPORTS_SEED: {
  name: string;
  city: string;
  country: string;
  code: string;
}[] = [
  { name: 'Шереметьево', city: 'Москва', country: 'Россия', code: 'SVO' },
  { name: 'Домодедово', city: 'Москва', country: 'Россия', code: 'DME' },
  {
    name: 'Пулково',
    city: 'Санкт-Петербург',
    country: 'Россия',
    code: 'LED',
  },
  { name: 'Сочи', city: 'Сочи', country: 'Россия', code: 'AER' },
  { name: 'Внуково', city: 'Москва', country: 'Россия', code: 'VKO' },
  { name: 'Жуковский', city: 'Москва', country: 'Россия', code: 'ZIA' },
  {
    name: 'Кольцово',
    city: 'Екатеринбург',
    country: 'Россия',
    code: 'SVX',
  },
  {
    name: 'Толмачёво',
    city: 'Новосибирск',
    country: 'Россия',
    code: 'OVB',
  },
  { name: 'Пашковский', city: 'Краснодар', country: 'Россия', code: 'KRR' },
  { name: 'Уфа', city: 'Уфа', country: 'Россия', code: 'UFA' },
  { name: 'Казань', city: 'Казань', country: 'Россия', code: 'KZN' },
  {
    name: 'Платов',
    city: 'Ростов-на-Дону',
    country: 'Россия',
    code: 'ROV',
  },
  { name: 'Курумоч', city: 'Самара', country: 'Россия', code: 'KUF' },
  {
    name: 'Толмачёво',
    city: 'Новосибирск',
    country: 'Россия',
    code: 'OVB',
  },
  { name: 'Храброво', city: 'Калининград', country: 'Россия', code: 'KGD' },
  {
    name: 'Емельяново',
    city: 'Красноярск',
    country: 'Россия',
    code: 'KJA',
  },
  {
    name: 'Владивосток',
    city: 'Владивосток',
    country: 'Россия',
    code: 'VVO',
  },
  {
    name: 'Стригино',
    city: 'Нижний Новгород',
    country: 'Россия',
    code: 'GOJ',
  },
  { name: 'Гумрак', city: 'Волгоград', country: 'Россия', code: 'VOG' },
  { name: 'Кневичи', city: 'Артём', country: 'Россия', code: 'VVO' },
  { name: 'Большое Савино', city: 'Пермь', country: 'Россия', code: 'PEE' },
  { name: 'Рощино', city: 'Тюмень', country: 'Россия', code: 'TJM' },
  { name: 'Иркутск', city: 'Иркутск', country: 'Россия', code: 'IKT' },
  { name: 'Новый', city: 'Хабаровск', country: 'Россия', code: 'KHV' },
  {
    name: 'Минеральные Воды',
    city: 'Минеральные Воды',
    country: 'Россия',
    code: 'MRV',
  },
  { name: 'Богашёво', city: 'Томск', country: 'Россия', code: 'TOF' },
  {
    name: 'Симферополь',
    city: 'Симферополь',
    country: 'Россия',
    code: 'SIP',
  },
  { name: 'Баландино', city: 'Челябинск', country: 'Россия', code: 'CEK' },
  {
    name: 'Кольцово',
    city: 'Екатеринбург',
    country: 'Россия',
    code: 'SVX',
  },
  { name: 'Бегишево', city: 'Нижнекамск', country: 'Россия', code: 'NBC' },
  { name: 'Уйташ', city: 'Махачкала', country: 'Россия', code: 'MCX' },
  { name: 'Сокол', city: 'Магадан', country: 'Россия', code: 'GDX' },
  { name: 'Мурманск', city: 'Мурманск', country: 'Россия', code: 'MMK' },
  {
    name: 'Елизово',
    city: 'Петропавловск-Камчатский',
    country: 'Россия',
    code: 'PKC',
  },
  {
    name: 'Хомутово',
    city: 'Южно-Сахалинск',
    country: 'Россия',
    code: 'UUS',
  },
  { name: 'Якутск', city: 'Якутск', country: 'Россия', code: 'YKS' },
  {
    name: 'Нарьян-Мар',
    city: 'Нарьян-Мар',
    country: 'Россия',
    code: 'NNM',
  },
  { name: 'Сургут', city: 'Сургут', country: 'Россия', code: 'SGC' },
  { name: 'Чертовицкое', city: 'Воронеж', country: 'Россия', code: 'VOZ' },
  { name: 'Курган', city: 'Курган', country: 'Россия', code: 'KRO' },
  { name: 'Барнаул', city: 'Барнаул', country: 'Россия', code: 'BAX' },
  { name: 'Абакан', city: 'Абакан', country: 'Россия', code: 'ABA' },
  { name: 'Череповец', city: 'Череповец', country: 'Россия', code: 'CEE' },
  { name: 'Сыктывкар', city: 'Сыктывкар', country: 'Россия', code: 'SCW' },
  { name: 'Астрахань', city: 'Астрахань', country: 'Россия', code: 'ASF' },
  { name: 'Оренбург', city: 'Оренбург', country: 'Россия', code: 'REN' },
  { name: 'Кемерово', city: 'Кемерово', country: 'Россия', code: 'KEJ' },
  { name: 'Саранск', city: 'Саранск', country: 'Россия', code: 'SKX' },
  { name: 'Ульяновск', city: 'Ульяновск', country: 'Россия', code: 'ULY' },
  { name: 'Грозный', city: 'Грозный', country: 'Россия', code: 'GRV' },
  {
    name: 'Благовещенск',
    city: 'Благовещенск',
    country: 'Россия',
    code: 'BQS',
  },
];
